import "./globals.css";
import sx from "@/styles/layout.module.scss"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header, Navigation } from "@/components";
import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import 'material-icons/iconfont/material-icons.css'
import { Providers } from "./providers";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type RootLayoutProps = {
    children: React.ReactNode;
}

export default function RootLayout({children}: RootLayoutProps) {
    library.add(fas)

    const navItems = [
        {
            url: "/dashboard",
            icon: "home"
        },
        {
            url: "/guests",  
            icon: "users"
        },
        {
            url: "/tables",
            icon: "table-cells"
        }
    ]

    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <section className={sx["main_content"]}>
                        {children}
                    </section>
                    <Navigation items={navItems}/>
                </Providers>
                {/* <div id="modal-root">{modal}</div>
                <div id="drawer-root">{drawer}</div> */}
            </body>
        </html>
    ); 
}
